[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
rayon = "1.10.0"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "1.0.65"
